//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod borrower;
pub mod consumer_debt;
pub mod existing_loans;
pub mod income_information;
pub mod loan_information;
pub mod mortgage_refinance;
pub mod new_loan_details;
pub mod benefit_to_borrower;
pub mod other_fees;
pub mod pricing_options;
pub mod savings_calculations;
pub mod settings;
