//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

// Organized entity modules
pub mod client;
pub mod income;
pub mod loans;
pub mod refinance;
pub mod calculations;
pub mod settings;

// Re-export entities at the top level for backward compatibility
pub use client::{borrower, timeline_events, outreach_templates, campaigns, ab_tests};
pub use income::{consumer_debt, income_information, w2_jobs};
pub use loans::{existing_loans, loan_information, new_loan_details};
pub use refinance::{mortgage_refinance, other_fees};
pub use calculations::{benefit_to_borrower, pricing_options, savings_calculations};
