//! SeaORM Entity. Generated by sea-orm-codegen 0.12.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sync_conflicts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub table_name: String,
    pub record_id: String,
    pub local_data: serde_json::Value,
    pub remote_data: serde_json::Value,
    pub local_version: i64,
    pub remote_version: i64,
    pub local_device_id: String,
    pub remote_device_id: String,
    pub status: String, // pending, resolved, ignored
    pub resolution: Option<serde_json::Value>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub resolved_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
