//! SeaORM Entity. Generated by sea-orm-codegen 0.12.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sync_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub table_name: String,
    pub record_id: String,
    pub operation: String, // INSERT, UPDATE, DELETE
    pub change_data: serde_json::Value,
    pub device_id: String,
    pub version: i64,
    pub timestamp: chrono::DateTime<chrono::Utc>,
    pub hash: String,
    pub is_synced: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
